# Basic Site Settings
title: "NITHYASHREE VELAYUTHAM PORTFOLIO"
description: "Welcome to my portfolio, showcasing my work in data science, machine learning, and more!"
url: "https://username.github.io" # Replace with your GitHub Pages URL
baseurl: "/" # Typically leave this as "/"

# Author Information
author:
  name: "Nithyashree Velayutham"
  email: "your.email@example.com" # Update with your email

# Theme Settings
theme: jekyll-theme-aesthetic

# Social Media Links
social_links:
  twitter: "https://twitter.com/yourusername"
  github: "https://github.com/yourusername"
  linkedin: "https://www.linkedin.com/in/yourusername"
  instagram: "https://www.instagram.com/yourusername" # Optional

# Navigation Menu
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Projects"
    url: "/projects/"
  - name: "Contact"
    url: "/contact/"

# Google Analytics (optional)
google_analytics: UA-XXXXX-Y # Replace with your own tracking ID if using Google Analytics

# Permalink Style
permalink: /:year/:month/:day/:slug/

# Pagination (if you want to paginate projects)
paginate: 5 # Number of projects per page
paginate_path: "/page:num/"

# Exclude unwanted files or folders from being built
exclude:
  - README.md
  - LICENSE.md

# Markdown and Code Syntax Highlighter Settings
markdown: kramdown # Default markdown parser
highlighter: rouge # Syntax highlighter for code blocks

# Plugins (Optional, you can add Jekyll plugins for additional functionality)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Additional Customizations
header_image: "/assets/images/portfolio_header.jpg" # Add your custom image for header

# Custom HTML or CSS (optional)
# Uncomment and add custom code here if you need any specific customization
# custom_css: "/assets/css/custom.css"

# Show download links for your work (if applicable)
show_downloads: true # Set to false if you don't want to show downloads
