# Basic Site Settings
title: "NITHYASHREE VELAYUTHAM PORTFOLIO"
description: "Welcome to my portfolio, showcasing my work in data science, machine learning, and more!"
url: "https://username.github.io" # Replace with your GitHub Pages URL
baseurl: "/" # Typically leave this as "/"

# Author Information
author:
  name: "Nithyashree Velayutham"
  email: "your.email@example.com" # Update with your email

# Theme Settings
theme: jekyll-theme-aesthetic

